//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirManager.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Airline
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string IATA { get; set; }
        public string CEO { get; set; }
        public string Story { get; set; }
        public string Real { get; set; }
        public string From { get; set; }
        public string To { get; set; }
    
        public virtual Country Country { get; set; }
    }
}
